### ISSUE TITLE
WEncoder trained on e4e not working 

### ISSUE THREAD

**Issue by MISSEY** [yuval-alaluf/hyperstyle#75]
Hi, I have trained an encoder on e4e https://github.com/omertov/encoder4editing, as mentioned in the readme https://github.com/yuval-alaluf/hyperstyle/tree/main#pretrained-hyperstyle-models. But it seems that support for e4e is missing, as I couldn't find e4e model initializing in the repo - https://github.com/yuval-alaluf/hyperstyle/blob/main/models/hyperstyle.py#L145. 

This is my execution command : 

```bash
python scripts/train.py \
    --dataset_type=phenodataset \
    --encoder_type=SharedWeightsHyperNetResNet \
    --exp_dir=experiments/hyperstyle \
    --workers=8 \
    --batch_size=8 \
    --test_batch_size=8 \
    --test_workers=8 \
    --val_interval=5000 \
    --save_interval=2000 \
    --lpips_lambda=0.8 \
    --l2_lambda=1 \
    --id_lambda=0 \
    --moco_lambda=0.5 \
    --n_iters_per_batch=5 \
    --max_val_batches=150 \
    --output_size=1024 \
    --load_w_encoder \
    --stylegan_weights /netscratch/smishra/gan_inversion/hyperstyle/pretrained_models/network-snapshot-015974_gan_inv.pt \
    --w_encoder_checkpoint_path /netscratch/smishra/gan_inversion/hyperstyle/pretrained_models/phenobench_w_encoder.pt
```

Error : 

```bash
Loading WEncoder from checkpoint: /netscratch/smishra/gan_inversion/hyperstyle/pretrained_models/phenobench_w_encoder.pt
Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main()
  File "scripts/train.py", line 19, in main
    coach = Coach(opts)
  File "./training/coach_hyperstyle.py", line 35, in __init__
    self.net = HyperStyle(self.opts).to(self.device)
  File "./models/hyperstyle.py", line 25, in __init__
    self.load_weights()
  File "./models/hyperstyle.py", line 61, in load_weights
    self.w_encoder = self.__get_pretrained_w_encoder()
  File "./models/hyperstyle.py", line 145, in __get_pretrained_w_encoder
    w_net = pSp(opts_w_encoder)
  File "./models/encoders/psp.py", line 33, in __init__
    self.load_weights()
  File "./models/encoders/psp.py", line 46, in load_weights
    self.encoder.load_state_dict(get_keys(ckpt, 'encoder'), strict=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1070, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for WEncoder:
        Missing key(s) in state_dict: "linear.weight", "linear.bias". 
        Unexpected key(s) in state_dict: "styles.0.convs.0.weight", "styles.0.convs.0.bias", "styles.0.convs.2.weight", "styles.0.convs.2.bias", "styles.0.convs.4.weight", "styles.0.convs.4.bias", "styles.0.convs.6.weight", "styles.0.convs.6.bias", "styles.0.linear.weight", "styles.0.linear.bias", "styles.1.convs.0.weight", "styles.1.convs.0.bias", "styles.1.convs.2.weight", "styles.1.convs.2.bias", "styles.1.convs.4.weight", "styles.1.convs.4.bias", "styles.1.convs.6.weight", "styles.1.convs.6.bias", "styles.1.linear.weight", "styles.1.linear.bias", "styles.2.convs.0.weight", "styles.2.convs.0.bias", "styles.2.convs.2.weight", "styles.2.convs.2.bias", "styles.2.convs.4.weight", "styles.2.convs.4.bias", "styles.2.convs.6.weight", "styles.2.convs.6.bias", "styles.2.linear.weight", "styles.2.linear.bias", "styles.3.convs.0.weight", "styles.3.convs.0.bias", "styles.3.convs.2.weight", "styles.3.convs.2.bias", "styles.3.convs.4.weight", "styles.3.convs.4.bias", "styles.3.convs.6.weight", "styles.3.convs.6.bias", "styles.3.convs.8.weight", "styles.3.convs.8.bias", "styles.3.linear.weight", "styles.3.linear.bias", "styles.4.convs.0.weight", "styles.4.convs.0.bias", "styles.4.convs.2.weight", "styles.4.convs.2.bias", "styles.4.convs.4.weight", "styles.4.convs.4.bias", "styles.4.convs.6.weight", "styles.4.convs.6.bias", "styles.4.convs.8.weight", "styles.4.convs.8.bias", "styles.4.linear.weight", "styles.4.linear.bias", "styles.5.convs.0.weight", "styles.5.convs.0.bias", "styles.5.convs.2.weight", "styles.5.convs.2.bias", "styles.5.convs.4.weight", "styles.5.convs.4.bias", "styles.5.convs.6.weight", "styles.5.convs.6.bias", "styles.5.convs.8.weight", "styles.5.convs.8.bias", "styles.5.linear.weight", "styles.5.linear.bias", "styles.6.convs.0.weight", "styles.6.convs.0.bias", "styles.6.convs.2.weight", "styles.6.convs.2.bias", "styles.6.convs.4.weight", "styles.6.convs.4.bias", "styles.6.convs.6.weight", "styles.6.convs.6.bias", "styles.6.convs.8.weight", "styles.6.convs.8.bias", "styles.6.linear.weight", "styles.6.linear.bias", "styles.7.convs.0.weight", "styles.7.convs.0.bias", "styles.7.convs.2.weight", "styles.7.convs.2.bias", "styles.7.convs.4.weight", "styles.7.convs.4.bias", "styles.7.convs.6.weight", "styles.7.convs.6.bias", "styles.7.convs.8.weight", "styles.7.convs.8.bias", "styles.7.convs.10.weight", "styles.7.convs.10.bias", "styles.7.linear.weight", "styles.7.linear.bias", "styles.8.convs.0.weight", "styles.8.convs.0.bias", "styles.8.convs.2.weight", "styles.8.convs.2.bias", "styles.8.convs.4.weight", "styles.8.convs.4.bias", "styles.8.convs.6.weight", "styles.8.convs.6.bias", "styles.8.convs.8.weight", "styles.8.convs.8.bias", "styles.8.convs.10.weight", "styles.8.convs.10.bias", "styles.8.linear.weight", "styles.8.linear.bias", "styles.9.convs.0.weight", "styles.9.convs.0.bias", "styles.9.convs.2.weight", "styles.9.convs.2.bias", "styles.9.convs.4.weight", "styles.9.convs.4.bias", "styles.9.convs.6.weight", "styles.9.convs.6.bias", "styles.9.convs.8.weight", "styles.9.convs.8.bias", "styles.9.convs.10.weight", "styles.9.convs.10.bias", "styles.9.linear.weight", "styles.9.linear.bias", "styles.10.convs.0.weight", "styles.10.convs.0.bias", "styles.10.convs.2.weight", "styles.10.convs.2.bias", "styles.10.convs.4.weight", "styles.10.convs.4.bias", "styles.10.convs.6.weight", "styles.10.convs.6.bias", "styles.10.convs.8.weight", "styles.10.convs.8.bias", "styles.10.convs.10.weight", "styles.10.convs.10.bias", "styles.10.linear.weight", "styles.10.linear.bias", "styles.11.convs.0.weight", "styles.11.convs.0.bias", "styles.11.convs.2.weight", "styles.11.convs.2.bias", "styles.11.convs.4.weight", "styles.11.convs.4.bias", "styles.11.convs.6.weight", "styles.11.convs.6.bias", "styles.11.convs.8.weight", "styles.11.convs.8.bias", "styles.11.convs.10.weight", "styles.11.convs.10.bias", "styles.11.linear.weight", "styles.11.linear.bias", "styles.12.convs.0.weight", "styles.12.convs.0.bias", "styles.12.convs.2.weight", "styles.12.convs.2.bias", "styles.12.convs.4.weight", "styles.12.convs.4.bias", "styles.12.convs.6.weight", "styles.12.convs.6.bias", "styles.12.convs.8.weight", "styles.12.convs.8.bias", "styles.12.convs.10.weight", "styles.12.convs.10.bias", "styles.12.linear.weight", "styles.12.linear.bias", "styles.13.convs.0.weight", "styles.13.convs.0.bias", "styles.13.convs.2.weight", "styles.13.convs.2.bias", "styles.13.convs.4.weight", "styles.13.convs.4.bias", "styles.13.convs.6.weight", "styles.13.convs.6.bias", "styles.13.convs.8.weight", "styles.13.convs.8.bias", "styles.13.convs.10.weight", "styles.13.convs.10.bias", "styles.13.linear.weight", "styles.13.linear.bias", "styles.14.convs.0.weight", "styles.14.convs.0.bias", "styles.14.convs.2.weight", "styles.14.convs.2.bias", "styles.14.convs.4.weight", "styles.14.convs.4.bias", "styles.14.convs.6.weight", "styles.14.convs.6.bias", "styles.14.convs.8.weight", "styles.14.convs.8.bias", "styles.14.convs.10.weight", "styles.14.convs.10.bias", "styles.14.linear.weight", "styles.14.linear.bias", "styles.15.convs.0.weight", "styles.15.convs.0.bias", "styles.15.convs.2.weight", "styles.15.convs.2.bias", "styles.15.convs.4.weight", "styles.15.convs.4.bias", "styles.15.convs.6.weight", "styles.15.convs.6.bias", "styles.15.convs.8.weight", "styles.15.convs.8.bias", "styles.15.convs.10.weight", "styles.15.convs.10.bias", "styles.15.linear.weight", "styles.15.linear.bias", "styles.16.convs.0.weight", "styles.16.convs.0.bias", "styles.16.convs.2.weight", "styles.16.convs.2.bias", "styles.16.convs.4.weight", "styles.16.convs.4.bias", "styles.16.convs.6.weight", "styles.16.convs.6.bias", "styles.16.convs.8.weight", "styles.16.convs.8.bias", "styles.16.convs.10.weight", "styles.16.convs.10.bias", "styles.16.linear.weight", "styles.16.linear.bias", "styles.17.convs.0.weight", "styles.17.convs.0.bias", "styles.17.convs.2.weight", "styles.17.convs.2.bias", "styles.17.convs.4.weight", "styles.17.convs.4.bias", "styles.17.convs.6.weight", "styles.17.convs.6.bias", "styles.17.convs.8.weight", "styles.17.convs.8.bias", "styles.17.convs.10.weight", "styles.17.convs.10.bias", "styles.17.linear.weight", "styles.17.linear.bias", "latlayer1.weight", "latlayer1.bias", "latlayer2.weight", "latlayer2.bias". 
```

Should I use PSP or what code modification I need to do to use e4e encoder ? 

Thank you

**Comment by yuval-alaluf** [comment]
You should be able to add support for e4e with a very small change. If I remember correctly, you just need to change the following lines: 
https://github.com/yuval-alaluf/hyperstyle/blob/a723c7310312ca5b7f859340027f78e18965acbc/models/hyperstyle.py#L138-L149
Rather than using `pSp` here, you can call the `e4e` class found [here](https://github.com/yuval-alaluf/hyperstyle/blob/main/models/encoders/e4e.py). 
You'll also want to change the encoder type using the `opts.w_encoder_type` value, which is set to `WEncoder` by default. You'll want to change this to the encoder type that you use for training your e4e model (e.g., set `--w_encoder_type=<TYPE>`.
I believe that should work, but let me know if you encounter any more problems.

**Comment by MISSEY** [comment]
Thank you @yuval-alaluf , my trained Restyle encoder (https://github.com/yuval-alaluf/restyle-encoder) with `ResNetProgressiveBackboneEncoder` on custom dataset has following settings : 

```json

{
'batch_size': 24,
 'board_interval': 50,
 'checkpoint_path': None,
 'd_reg_every': 16,
 'dataset_type': 'phenobench',
 'delta_norm': 2,
 'delta_norm_lambda': 0.0002,
 'encoder_type': 'ResNetProgressiveBackboneEncoder',
 'exp_dir': 'experiment/restyle_e4e_phenobench4',
 'id_lambda': 0.0,
 'image_interval': 100,
 'input_nc': 6,
 'l2_lambda': 1.0,
 'learning_rate': 0.0001,
 'lpips_lambda': 0.8,
 'max_steps': 100000,
 'moco_lambda': 0.5,
 'n_iters_per_batch': 5,
 'optim_name': 'ranger',
 'output_size': 1024,
 'progressive_start': 20000,
 'progressive_step_every': 2000,
 'progressive_steps': [0,
                       20000,
                       22000,
                       24000,
                       26000,
                       28000,
                       30000,
                       32000,
                       34000,
                       36000,
                       38000,
                       40000,
                       42000,
                       44000,
                       46000,
                       48000,
                       50000,
                       52000],
 'r1': 10,
 'resume_training_from_ckpt': None,
 'save_interval': 10000,
 'save_training_data': False,
 'start_from_latent_avg': True,
 'stylegan_weights': '/netscratch/smishra/gan_inversion/hyperstyle/pretrained_models/network-snapshot-015974_gan_inv.pt',
 'sub_exp_dir': None,
 'test_batch_size': 8,
 'test_workers': 8,
 'train_decoder': False,
 'update_param_list': None,
 'use_w_pool': True,
 'val_interval': 5000,
 'w_discriminator_lambda': 0.1,
 'w_discriminator_lr': 2e-05,
 'w_norm_lambda': 0.0,
 'w_pool_size': 50,
 'workers': 8
}
Loading encoders weights from resnet34!

```
**Comand I used to train the hyperstyle**

```bash
python scripts/train.py \
    --dataset_type=phenobench \
    --encoder_type=SharedWeightsHyperNetResNet \
    --exp_dir=experiments/e4e \
    --workers=8 \
    --batch_size=32 \
    --test_batch_size=8 \
    --test_workers=8 \
    --val_interval=5000 \
    --save_interval=2000 \
    --lpips_lambda=0.8 \
    --l2_lambda=1 \
    --id_lambda=0 \
    --moco_lambda=0.5 \
    --max_steps=100000 \
    --n_iters_per_batch=5 \
    --max_val_batches=150 \
    --output_size=1024 \
    --load_w_encoder \
    --stylegan_weights /netscratch/smishra/gan_inversion/hyperstyle/pretrained_models/network-snapshot-015974_gan_inv.pt \
    --w_encoder_checkpoint_path /netscratch/smishra/gan_inversion/restyle-encoder/experiment/restyle_e4e_phenobench4/checkpoints/best_model.pt \
    --w_encoder_type=ResNetProgressiveBackboneEncoder
```
Having the following size mismatch error : 

```bash
RuntimeError: Error(s) in loading state_dict for ResNetProgressiveBackboneEncoder:
        size mismatch for conv1.weight: copying a param with shape torch.Size([64, 6, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 3, 7, 7]).
```

**Comment by MISSEY** [comment]
I have checked,the input_nc argument is set to 6 in both hyperstyle and restyle.

**Comment by yuval-alaluf** [comment]
I believe you'll want to change the following line to `6` in the function I sent above: 
https://github.com/yuval-alaluf/hyperstyle/blob/a723c7310312ca5b7f859340027f78e18965acbc/models/hyperstyle.py#L143
By default, we assumed that the encoder is a WEncoder with 3 channels as input. If you used ReStyle, then you'll want to set this as 6.

**Comment by MISSEY** [comment]
There is an additional error on https://github.com/yuval-alaluf/hyperstyle/blob/main/models/hyperstyle.py#L159

```bash
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 6, 7, 7], expected input[2, 3, 256, 256] to have 6 channels, but got 3 channels instead
```

I compared with restyle official implementation - https://github.com/yuval-alaluf/restyle-encoder/blob/main/models/e4e.py#L56, 

```python
def forward(self, x, latent=None, resize=True, latent_mask=None, input_code=False, randomize_noise=True,
                inject_latent=None, return_latents=False, alpha=None, average_code=False, input_is_full=False):
        if input_code:
            codes = x
        else:
            codes = self.encoder(x)
```

The size of x is [N,6,256,256] which is concatenate with input and latent_average_code:
https://github.com/yuval-alaluf/restyle-encoder/blob/main/training/coach_restyle_e4e.py#L127

```python
avg_image_for_batch = self.avg_image.unsqueeze(0).repeat(x.shape[0], 1, 1, 1)
				x_input = torch.cat([x, avg_image_for_batch], dim=1)
```
Should I also concatenate the input with latent_average_code before passing to the encoder here - https://github.com/yuval-alaluf/hyperstyle/blob/main/models/hyperstyle.py#L159 ?

**Comment by MISSEY** [comment]
I changed the implementation a little bit and it worked! https://github.com/yuval-alaluf/hyperstyle/commit/f73df749d3ae5820e8bac6db3e69f992ed2c3160
